general.import = ["./themes/catppuccin-mocha.toml"]

general.working_directory = "C:/Users/Nadir"

terminal.shell = "pwsh"

[font]
size = 13

[font.normal]
family = "Hack Nerd Font"

[window]
# decorations = "None"
# startup_mode = "Maximized"
opacity = 0.95
